//! End-to-end tests for `FfmpegProbe` against tiny on-disk fixtures.
//!
//! Fixtures are generated by `scripts/generate_fixtures.sh`; if they are
//! missing, each test is skipped with an explanatory message rather than
//! hard-failing, so a fresh clone that hasn't run `make fixtures` yet still
//! gets a green `cargo test`.

use std::path::{Path, PathBuf};

use reel_core::{FfmpegProbe, MediaProbe};

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
}

fn maybe_skip(path: &Path) -> bool {
    if !path.exists() {
        eprintln!("fixture missing: {} — run `make fixtures`", path.display());
        return true;
    }
    false
}

#[test]
fn probes_video_with_audio() {
    let p = fixtures_dir().join("tiny_h264_aac.mp4");
    if maybe_skip(&p) {
        return;
    }
    let md = FfmpegProbe::new().probe(&p).unwrap();
    let v = md.video.expect("video stream present");
    assert_eq!(v.width, 64);
    assert_eq!(v.height, 64);
    assert!(md.audio.is_some(), "audio decoded");
    assert!(!md.audio_disabled);
}

#[test]
fn probes_video_only() {
    let p = fixtures_dir().join("no_audio.mp4");
    if maybe_skip(&p) {
        return;
    }
    let md = FfmpegProbe::new().probe(&p).unwrap();
    assert!(md.video.is_some());
    assert!(md.audio.is_none());
    assert!(!md.audio_disabled, "no audio stream != audio_disabled");
}

#[test]
fn probes_nonexistent_file_errors() {
    let p = fixtures_dir().join("definitely-not-here.mp4");
    let err = FfmpegProbe::new().probe(&p).unwrap_err();
    let msg = err.to_string();
    assert!(
        msg.contains("i/o") || msg.contains("not found"),
        "got {msg}"
    );
}
